common_tasks:
  - Implementação de Código
  - Implementação de Código
  - Implementação de Código
  - Correção de Bug
  - Testes de funcionalidade
  - Deploy no ambiente
  - Tempo disponível
  - Tempo reservado para estudo
  #  - Análise da documentação do projeto
  #  - Validação de Casos de Uso
  #  - Atualização de Documentação

max_task_duration: 180
minutes_per_day:
  min: 360
  max: 600

pause:
  min: 0
  max: 30

task_per_day:
  min: 3
  max: 10

task_variation:
  min: -30
  max: 60

periods:
  start_time: !time "08:00"
  lunch_start: !time "12:00"
  lunch_end: !time "14:00"
  comercial_end: !time "18:00"
  end_time: !time "21:00"